config/routes.rb
Rails.application.routes.draw do
  resources :missions

  root "missions#index"

  resources :users, only: [:create] do
		collection do
			get :sign_up   
			get :sign_in
		end
	end

	post "/users/sign_in", to: "sessions#create", as: "login"
	delete "/users", to: "sessions#destroy", as: "logout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mission.rb
class Mission < ApplicationRecord
  validates :title, presence: true
  validates :started_at, presence: true
  validates :finished_at, presence: true

  belongs_to :user
end

app/models/user.rb
require "digest"

class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true

  has_many :missions, dependent: :destroy

  before_create :encrypt_password

  def encrypt_password
    salted_pw = "aovger#{self.password}348950#{self.password}sfj246-540zco"
    self.password = Digest::SHA1.hexdigest(salted_pw)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  helper_method :user_signed_in?, :current_user
  
  private

  def user_signed_in?
    session[:rubyisgoodforlife] != nil
  end

  def current_user
    if user_signed_in?
      User.find(session[:rubyisgoodforlife])
    else
      nil
    end
  end

  def authenticate_user!
    if not user_signed_in?
      redirect_to login_path
    end
  end

  def record_not_found
    render file "public/404.html", status: :not_found
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_mission, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! 
  
  def index
    @missions = current_user.missions.order(id: :desc)
  end

  def new
    @mission = current_user.missions.new
  end

  def create
    @mission = current_user.missions.new(mission_params)
    
    if @mission.save
      redirect_to missions_path
    else
      render :new
    end  
  end

  def edit
  end

  def show
  end

  def update
    if @mission.update(mission_params)
      redirect_to mission_path(@mission)
    else  
      render :edit  
    end
  end

  def destroy
    @mission.destroy
    redirect_to missions_path
  end

  private

  def mission_params
    params.require(:mission).permit(:title, :description, :started_at, :finished_at)
  end

  def set_mission
    @mission = current_user.missions.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    pw = user_params[:password]
    salted_pw = "aovger#{pw}348950#{pw}sfj246-540zco"
    hashed_pw = Digest::SHA1.hexdigest(salted_pw)
    
    user = User.find_by(email: user_params[:email], 
                        password: hashed_pw 
                       ) 
    if user
      session[:rubyisgoodforlife] = user.id
      redirect_to root_path
    else
      redirect_to sign_in_users_path  
    end                   
  end

  def destroy
    session[:rubyisgoodforlife] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_up
    @user = User.new
  end

  def sign_in
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render :sign_up
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MissionManagerDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
        <%= render "shared/navbar" %>
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/missions/_form.html.erb
<div class="row justify-content-center">
  <div class="col-6">
    <%= form_for mission do |f| %>       
      <div class="mb-3">
        <%= f.label :title, 'Title', class: "form-lable" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :description, 'Description', class: "form-lable" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :started_at, 'Start time', class: "form-lable" %>
        <%= f.datetime_field :started_at, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :finished_at, 'Finish time', class: "form-lable" %>
        <%= f.datetime_field :finished_at, class: "form-control" %>
      </div>
      <%= f.submit "Submit", disable_with: 'Submiting...', class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/missions/edit.html.erb
<div class="row text-center">
  <h1>Edit Mission</h1>
</div>

<div class="row justify-content-end">
  <div class="col-3">
    <%= link_to "Back To List", missions_path, class: "btn btn-primary" %>
  </div>
</div>

<%= render "form", mission: @mission %>

app/views/missions/index.html.erb
<h1 class="text-center text-dark">Missions List</h1>
<div class="row justify-content-end">
  <div class="col-3">
    <%= link_to "Add New Mission", new_mission_path, class: "btn btn-primary" %>
  </div>
</div>

<div class="row">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Start</th>
        <th scope="col">Finish</th>
        <th scope="col">Operate</th>
      </tr>
    </thead>
    <tbody>
      <% @missions.each do |mission| %>
      <tr>
        <td><%= link_to "#{mission.title}", mission_path(mission)%></td>
        <td><%= link_to "#{mission.description}", mission_path(mission)%></td>
        <td><%= mission.started_at.strftime("%Y-%m-%d") %></td>
        <td><%= mission.finished_at.strftime("%Y-%m-%d") %></td>
        <td>
          <%= link_to "Edit", edit_mission_path(mission), class: "btn btn-xs" %>
          <%= link_to "Delete", mission_path(mission), class: "btn btn-xs", method: "delete", data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/missions/new.html.erb
<div class="row text-center">
  <h1>New Mission</h1>
</div>

<div class="row justify-content-end">
  <div class="col-3">
    <%= link_to "Back To List", missions_path, class: "btn btn-primary" %>
  </div>
</div>

<%= render "form", mission: @mission %>

app/views/missions/show.html.erb
<h1 class="text-center text-dark"><%= @mission.title %></h1>
<div class="row justify-content-end">
  <div class="col-3">
    <%= link_to "Back To List", missions_path, class: "btn btn-primary" %>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <p>任務內容：</p>
    <p><%= @mission.description %></p>
  </div>
</div>
<div class="row justify-content-end">
  <div class="col-2">
    <p>Start time</p>
    <%= @mission.started_at.strftime("%Y-%m-%d") %>
  </div>
  <div class="col-2">
    <p>Finish time:</p>
    <%= @mission.finished_at.strftime("%Y-%m-%d") %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Mission Manager</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if !current_user %>
          <li class="nav-item">
            <%= link_to "sign in", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "sign up", sign_up_users_path, class: "nav-link" %>
          </li>  
        <% else %>
          <li class="nav-item">
            Hi, <%= current_user.username %>
          </li>
          <li class="nav-item">
            <%= link_to "log out", logout_path, method: "DELETE", class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/users/sign_in.html.erb
<h1>Log in</h1>

<%= form_for(@user, url: login_path) do |f| %>
  <div class="mb-3">
    <%= f.label :email, "E-mail", class: "form-lable" %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :password, "Password", class: "form-lable" %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <%= f.submit "Log in", disable_with: "Submiting...", class: "btn btn-primary" %>
<% end %> 

app/views/users/sign_up.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="row justify-content-center">
  <div class="col-6">
    <%= form_for(@user, url: "/users") do |f| %>       
      <div class="mb-3">
        <%= f.label :email, "E-mail", class: "form-lable" %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :username, "Username", class: "form-lable" %>
        <%= f.text_field :username, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :password, "Password", class: "form-lable" %>
        <%= f.text_field :password, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :password_confirmation, "Password confirmation", class: "form-lable" %>
        <%= f.text_field :password_confirmation, class: "form-control" %>
      </div>
      <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
    <% end %>
  </div>
</div>